require:
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 2.4
  DefaultFormatter: progress
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
   - 'bin/*'
   - '*.md'

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'mirah-ruby.gemspec'

Naming/MethodParameterName:
  AllowedNames:
    - io
    - id
    - to
    - by
    - 'on'
    - in
    - at
    - ip
    - db
    - tz
    - el
    - e

RSpec/ExampleLength:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/NestedGroups:
  Max: 7

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleExpectations:
  Enabled: false
