version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  test24:
    docker:
      - image: cimg/ruby:2.4
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Configure Bundler
          command: |
            gem install bundler
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: Tests
          command: bundle exec rake spec
  test25:
    docker:
      - image: cimg/ruby:2.5
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Configure Bundler
          command: |
            gem install bundler
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: Tests
          command: bundle exec rake spec
  test26:
    docker:
      - image: cimg/ruby:2.6
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=2.1.4' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: Tests
          command: bundle exec rake spec
  test27:
    docker:
      - image: cimg/ruby:2.7
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=2.1.4' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: Tests
          command: bundle exec rake spec
  test31:
    docker:
      - image: cimg/ruby:3.1.2
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=2.1.4' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: Tests
          command: bundle exec rake spec



workflows:
  version: 2
  test:
    jobs:
      - test24
      - test25
      - test26
      - test27
      - test31

      