version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  test24:
    docker:
      - image: circleci/ruby:2.4.6-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=1.16.6' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: Tests
          command: bundle exec rake spec
  test25:
    docker:
      - image: circleci/ruby:2.5-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=1.16.6' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: Tests
          command: bundle exec rake spec
  test26:
    docker:
      - image: circleci/ruby:2.6-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=2.1.4' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: Tests
          command: bundle exec rake spec
  test27:
    docker:
      - image: circleci/ruby:2.7-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=2.1.4' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: Tests
          command: bundle exec rake spec


workflows:
  version: 2
  test:
    jobs:
      - test24
      - test25
      - test26
      - test27

      